apiVersion: v1
kind: Pod
metadata:
  name: pod0
  namespace: default
spec:
  nodeName: worker-3
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
spec:
  nodeName: worker-2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: default
spec:
  nodeName: worker-2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: default
spec:
  nodeName: worker-2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: default
spec:
  nodeName: worker-2
